/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cbaeza.shell_integrator;

import com.cbaeza.shell_integrator.command.LsCommand;
import com.cbaeza.shell_integrator.service.SomeBuildService;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
        LsCommand lsCommand = new LsCommand(new SomeBuildService());
        lsCommand.listAll("ALL");
    }
}
